### ISSUE TITLE
reproduce the meta-material benchmark

### ISSUE THREAD

**Issue by ThyrixYang** [BensonRen/idlm_Pytorch#1]
Hi, 

I'm fairly interested in your NeurIPS 2020 paper. However, it seems that the model needed in the meta-material benchmark is not included in this repo. Could you please help me to reproduce your results on this benchmark?

**Comment by BensonRen** [comment]
Hi, thank you so much for your interest! 

First of all, this repo is sort of my playground where code is unorganized and undocumented, https://github.com/BensonRen/BDIMNNA should be the official paper repo.

Secondly, in that official repo, there is still some issue with the environment and path that I need to fix, sorry I haven't fix those due to final weeks...

That full repo should be up before the NIPS conference date within 2 weeks, there should be a one-click interface where the models can be trained and evaluated and the environment and paths should be more user-friendly.

**Comment by ThyrixYang** [comment]
Thanks for your timely reply!
I'm looking forward to the final revision.
